Add optional parameter to like(), or_like(), not_like() and or_not_like() methods.
bcit-ci/CodeIgniter pull request #5643
Opened 2018-11-27 13:48 UTC by Nudasoft

This PR address the 2nd feature request from this #5641 issue.

2018-12-12 22:14 UTC, narfbg commented
This is parameter creep ... It may look inconsistent, but a better option would be to just have `having_like()`, `having_not_like()`, etc.

And you must follow the [styleguide](https://www.codeigniter.com/user_guide/general/styleguide.html).

2019-01-02 02:11 UTC, Nudasoft commented
Is there anything I have to do in order to make this PR get merged?

2019-01-04 13:05 UTC, narfbg commented
Yes, there are still some spaces left in on lines 1100, 1171 (shown in diff with darker green).

And there's more significant stuff code-wise, but it will probably result in a lot of back and forth if I asked you to do all of it, so I can make those changes myself after merging. It's decent enough as it is, I just want less repetition.

2019-02-28 14:49 UTC, error56 requested changes
All the code doesn't match PSR-2 rules

2019-02-28 14:49 UTC, NallDev commented on system/database/DB_query_builder.php
> +	public function having_like($field, $match = '', $side = 'both', $escape = NULL)
this line doesn't match PSR-2 rules

2019-02-28 14:49 UTC, NallDev commented on system/database/DB_query_builder.php
> +	// --------------------------------------------------------------------
bad comment

2019-02-28 14:49 UTC, NallDev commented on system/database/DB_query_builder.php
> +	public function not_having_like($field, $match = '', $side = 'both', $escape = NULL)
this line doesn't match PSR-2 rules

2019-02-28 14:49 UTC, NallDev commented on system/database/DB_query_builder.php
> +	public function or_having_like($field, $match = '', $side = 'both', $escape = NULL)
this line doesn't match PSR-2 rules

2019-02-28 14:49 UTC, NallDev commented on system/database/DB_query_builder.php
> +	public function or_not_having_like($field, $match = '', $side = 'both', $escape = NULL)
this line doesn't match PSR-2 rules

2019-02-28 14:49 UTC, NallDev commented on system/database/DB_query_builder.php
> +	public function having_group_start($not = '', $type = 'AND ')
this line doesn't match PSR-2 rules

2019-02-28 14:49 UTC, NallDev commented on system/database/DB_query_builder.php
> +		$having = array(
You can use `[]`

2019-02-28 14:53 UTC, narfbg commented on system/database/DB_query_builder.php
> +	public function having_like($field, $match = '', $side = 'both', $escape = NULL)
We don't subscribe to PSR-2.

2019-02-28 14:54 UTC, narfbg commented on system/database/DB_query_builder.php
> +	// --------------------------------------------------------------------
It's not a "bad comment"; we have these in between all functions.

2019-02-28 14:54 UTC, narfbg commented on system/database/DB_query_builder.php
> +		$having = array(
... and I'd force him to change it back to `array()`, because that's what we use.

2019-02-28 14:57 UTC, narfbg commented
Yes, all of CodeIgniter doesn't match PSR-2 rules. We have our own [styleguide](https://www.codeigniter.com/user_guide/general/styleguide.html), referenced in the [contributing guide](https://github.com/bcit-ci/CodeIgniter/blob/develop/contributing.md), which you should read before reviewing others' work.

2022-01-08 20:49 UTC, narfbg requested changes

2022-01-08 20:49 UTC, narfbg commented on system/database/DB_query_builder.php
> +	public function not_having_like($field, $match = '', $side = 'both', $escape = NULL)
This should be `having_not_like` instead.
Same thing applies to all other methods below - `not` should always be after `having` in the name.

2026-06-02 03:46 UTC, closed without merging