Update captcha_helper.php
bcit-ci/CodeIgniter pull request #5999
Opened 2020-10-26 11:24 UTC by hhuseyincihangir

Updated captcha_helper for customizable image tag class.

- It is useful to give class in order for the captcha visual to be responsive (we can send img-fluid class with bootstrap).

2020-10-28 01:13 UTC, orionstar requested changes

2020-10-28 01:13 UTC, orionstar commented on system/helpers/captcha_helper.php
> +	function create_captcha($data = '', $img_path = '', $img_url = '', $img_tag_class = '', $font_path = '')
I think you should change the order of $img_tag_class and $font_path paramter to maintain compatibility with the previous signature of the function.

2020-11-03 15:38 UTC, orionstar approved these changes

2020-11-13 00:56 UTC, lazarospsa reviewed
👍🏼

2021-02-04 17:50 UTC, closed without merging