PHP 8 compatibility issues
bcit-ci/CodeIgniter pull request #6007
Opened 2020-12-17 18:41 UTC by blasto333

2020-12-17 18:49 UTC, gxgpet requested changes

2020-12-17 18:49 UTC, gxgpet commented on system/libraries/Migration.php
> +			elseif (!(class_exists($class) && in_array($method, get_class_methods($class))))
The style guide is not followed; see how was the `!` operator written before (the left and right space). Also, I see that there's an unnecessary pair of parentheses.

2020-12-17 19:00 UTC, blasto333 commented
@gxgpet I have made the changes. I also removed the check for class_exists is that is already taken care of before this elseif is called

2020-12-17 20:17 UTC, blasto333 commented
@gxgpet Also found another place of is_callable that won't work. So far these are all the PHP 8 issues I have found

2021-01-13 10:00 UTC, sapics commented on system/libraries/Session/Session.php
> +				//This is what we had to change for php 8
This comment said about your fixing, not about the code itself ;)
It looks better to write the fixing comment in the comment log.

2021-01-13 10:06 UTC, sapics commented on system/libraries/Session/Session.php
> +				elseif ($value === 'old')
At a glance, when $value is number, the result would be changed, I guess.
`$value === 'old' || $value < $current_time`
or
`$value === 'old' || (is_numeric($value) && $value < $current_time)`
looks better.

2021-02-04 15:34 UTC, closed without merging

2025-03-18 15:01 UTC, kitsites commented on system/libraries/Session/Session.php
> +				elseif ($value === 'old')
thank you so much