profiler.php PHP 8.1 deprecation notice
bcit-ci/CodeIgniter pull request #6100
Opened 2022-02-09 20:17 UTC by svennd

check for null value on $val

for this warning : 
`Message: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated`

I think there might be more cases, but I only fixed the case I ran into. (also not sure if this is a valid style of fixing)

2022-02-09 23:44 UTC, jamieburchell commented
Technically, '0' and 0 would be converted to '' (although an unlikely scenario). But I suspect that @narfbg will prefer you to cast `$val` to a string here instead:

`htmlspecialchars((string) $val)`

2022-02-10 07:54 UTC, svennd commented
Thanks for the feedback Jamie, I changed the update to string cast instead.

2022-02-11 14:28 UTC, narfbg requested changes

2022-02-11 14:28 UTC, narfbg commented on system/libraries/Profiler.php
> +				.$config.'&nbsp;&nbsp;</td><td style="padding:5px;color:#000;background-color:#ddd;">'.$pre.htmlspecialchars((string)$val, ENT_QUOTES, config_item('charset')).$pre_close."</td></tr>\n";
Should have a space in between. Same for the other line that's being changed ...

2022-02-11 15:35 UTC, svennd commented
Thanks for the feedback!

2022-02-12 16:39 UTC, narfbg requested changes

2022-02-12 16:39 UTC, narfbg commented on system/libraries/Profiler.php
> +				.$config.'&nbsp;&nbsp;</td><td style="padding:5px;color:#000;background-color:#ddd;">'.$pre.htmlspecialchars( (string) $val, ENT_QUOTES, config_item('charset')).$pre_close."</td></tr>\n";
*In between*, not around ... Just one space between the typecast and the variable.

2022-02-12 19:34 UTC, svennd commented on system/libraries/Profiler.php
> +				.$config.'&nbsp;&nbsp;</td><td style="padding:5px;color:#000;background-color:#ddd;">'.$pre.htmlspecialchars( (string) $val, ENT_QUOTES, config_item('charset')).$pre_close."</td></tr>\n";
Thanks for the patience :) fixed now !

2022-02-12 23:57 UTC, merged